# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Oksusutea's Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Oksusutea's blog

description: Stylish Jekyll Theme
author:
  name: oksusutea's blog
  email: cjkim0118@gmail.com
  github: oksusutea
  bio: 꾸준히 기록하려고 만든 블로그
  email_md5: bfb47fcb84782994a344ffb0ce6f8bb7


categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
